import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConfigProvider from "antd/es/config-provider";
import theme from "../utilites/themeConfig";
import Navbar from "../components/Navbar/Navbar";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConfigProvider theme={theme}>
          <div style={{ background: "#0D121F" }}>
            <Navbar />
            {children}
            <Footer />
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
