import type { Metadata } from "next";
import "./globals.css";
import ConfigProvider from "antd/es/config-provider";
import theme from "../utilites/themeConfig";
import Navbar from "../components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import GSAPProvider from '@/lib/gsap/GSAPProvider'



export const metadata: Metadata = {
  title: "Spend In",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ConfigProvider theme={theme}>
          <div style={{ background: "#0D121F" }}>
            <Navbar />
            <GSAPProvider>
              {children}
            </GSAPProvider>
            <Footer />
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
